import type { Place, Trip } from "./types";

export const PLACES: Record<string, Place> = {
  // Westernmost point on the map, so its label has to sit below the dot rather
  // than beside it or it runs off the frame.
  sfo: { id: "sfo", name: "San Francisco", country: "United States", code: "SFO", lon: -122.389, lat: 37.621, anchor: "s" },
  ord: { id: "ord", name: "Chicago", country: "United States", code: "ORD", lon: -87.904, lat: 41.978, anchor: "n" },
  dfw: { id: "dfw", name: "Dallas Fort Worth", country: "United States", code: "DFW", lon: -97.038, lat: 32.897, anchor: "w" },
  bze: { id: "bze", name: "Belize City", country: "Belize", code: "BZE", lon: -88.308, lat: 17.539, anchor: "s" },
  atl: { id: "atl", name: "Atlanta", country: "United States", code: "ATL", lon: -84.428, lat: 33.64, anchor: "e" },
  mad: { id: "mad", name: "Madrid", country: "Spain", code: "MAD", lon: -3.567, lat: 40.472, anchor: "n" },
  svq: { id: "svq", name: "Seville", country: "Spain", lon: -5.975, lat: 37.392, anchor: "s" },
  spu: { id: "spu", name: "Split", country: "Croatia", code: "SPU", lon: 16.298, lat: 43.539, anchor: "s" },
  // Krakow sits almost due north of Belgrade, so the two labels are pushed to
  // opposite sides to keep them apart.
  beg: { id: "beg", name: "Belgrade", country: "Serbia", code: "BEG", lon: 20.309, lat: 44.819, anchor: "e" },
  krk: { id: "krk", name: "Krakow", country: "Poland", code: "KRK", lon: 19.785, lat: 50.078, anchor: "w" },
  hel: { id: "hel", name: "Helsinki", country: "Finland", code: "HEL", lon: 24.963, lat: 60.317, anchor: "n" },
};

export const TRIPS: Trip[] = [
  {
    slug: "2026-belize-spain-balkans",
    title: "Belize, Spain, the Balkans, home the long way",
    blurb:
      "Five weeks going west to east and then all the way back: out of San Francisco, down to the Caribbean coast, across the Atlantic overnight, a slow drift from Madrid to Belgrade, and home into Chicago over the top of the world from Helsinki.",
    start: "2026-08-22",
    end: "2026-09-25",
    legs: [
      {
        from: "sfo",
        to: "ord",
        mode: "flight",
        date: "2026-08-22",
        depart: "17:07",
        arrive: "23:30",
        carrier: "American",
        number: "AA 2358",
      },
      {
        from: "ord",
        to: "dfw",
        mode: "flight",
        date: "2026-08-24",
        depart: "08:20",
        arrive: "10:57",
        carrier: "American",
        number: "AA 1555",
      },
      {
        from: "dfw",
        to: "bze",
        mode: "flight",
        date: "2026-08-24",
        depart: "12:27",
        arrive: "14:30",
        carrier: "American",
        number: "AA 319",
        note: "1h 30m connection at Dallas.",
      },
      {
        from: "bze",
        to: "atl",
        mode: "flight",
        date: "2026-08-30",
        depart: "12:15",
        arrive: "17:17",
        carrier: "Delta",
        number: "KLM 6512",
      },
      {
        from: "atl",
        to: "mad",
        mode: "flight",
        date: "2026-08-30",
        depart: "21:55",
        arrive: "12:15",
        arriveDate: "2026-08-31",
        carrier: "Delta",
        number: "KLM 6028",
        note: "4h 38m layover in Atlanta, then the overnight across the Atlantic.",
      },
      {
        from: "mad",
        to: "svq",
        mode: "train",
        date: "2026-09-01",
        depart: "14:05",
        arrive: "16:45",
        carrier: "Ouigo",
        number: "06546",
        note: "Madrid Puerta de Atocha to Seville Santa Justa.",
      },
      {
        from: "svq",
        to: "mad",
        mode: "train",
        date: "2026-09-05",
        unbooked: true,
        note: "Nothing booked for the way back yet, and the Madrid flight leaves on the 5th.",
      },
      {
        from: "mad",
        to: "spu",
        mode: "flight",
        date: "2026-09-05",
        depart: "13:50",
        arrive: "16:30",
        carrier: "Iberia",
        number: "IB 945",
      },
      {
        from: "spu",
        to: "beg",
        mode: "flight",
        date: "2026-09-13",
        depart: "15:20",
        arrive: "16:20",
        carrier: "Air Serbia",
        number: "JU 703",
      },
      {
        from: "beg",
        to: "krk",
        // Dated to the Belgrade checkout so it sorts after that stay; the label
        // is what actually gets shown.
        date: "2026-09-15",
        dateLabel: "15 to 25 Sept",
        mode: "flight",
        unbooked: true,
        modeUnknown: true,
        note: "Out of the Belgrade hotel on the 15th, then ten open days before the flight home leaves Krakow, with nothing booked to cover the ground between.",
      },
      {
        from: "krk",
        to: "hel",
        mode: "flight",
        date: "2026-09-25",
        depart: "12:30",
        arrive: "15:25",
        carrier: "Finnair",
        number: "AY 1166",
      },
      {
        from: "hel",
        to: "ord",
        mode: "flight",
        date: "2026-09-25",
        depart: "16:25",
        arrive: "17:50",
        carrier: "Finnair",
        number: "AY 009",
        note: "1h transfer in Helsinki, then 9h 25m westbound. The clock barely moves because you are chasing the time zones home.",
      },
    ],
    stays: [
      {
        placeId: "bze",
        name: "Fort George Hotel & Spa",
        from: "2026-08-29",
        to: "2026-08-30",
        nights: 1,
      },
      {
        placeId: "mad",
        name: "Thompson Madrid",
        from: "2026-08-31",
        to: "2026-09-01",
        nights: 1,
      },
      {
        placeId: "beg",
        name: "Courtyard Marriott Belgrade City Center",
        from: "2026-09-13",
        to: "2026-09-15",
        nights: 2,
      },
    ],
  },
];
