#!/usr/bin/env tsx
/**
 * Turns the world-atlas TopoJSON into flat SVG path strings in our Mercator
 * space and writes them to lib/travels/world-paths.ts.
 *
 *   npm run generate:map
 *
 * Run once. The output is committed, so the site ships no map library and the
 * page has no runtime dependency on this data ever being fetched.
 */
import fs from "fs";
import path from "path";
import { feature } from "topojson-client";
import type { Topology } from "topojson-specification";
import { project } from "../lib/travels/projection";

// 110m is the coarse resolution: right for a page-width map, and small enough
// that the whole world fits in a file worth committing.
const SOURCE = require.resolve("world-atlas/countries-110m.json");
const OUT = path.join(process.cwd(), "lib", "travels", "world-paths.ts");

type Ring = [number, number][];

interface Shape {
  d: string;
  /** [minX, minY, maxX, maxY], so the page can skip rings that are off-screen. */
  bbox: [number, number, number, number];
}

function ringToShape(ring: Ring): Shape | null {
  let minX = Infinity;
  let minY = Infinity;
  let maxX = -Infinity;
  let maxY = -Infinity;

  const points: string[] = [];
  for (const [lon, lat] of ring) {
    const [x, y] = project(lon, lat);
    const rx = Math.round(x);
    const ry = Math.round(y);
    if (rx < minX) minX = rx;
    if (ry < minY) minY = ry;
    if (rx > maxX) maxX = rx;
    if (ry > maxY) maxY = ry;
    // Integer precision: one unit is about one screen pixel at the sizes this
    // map is drawn, so the extra decimals were only inflating the payload.
    const point = `${rx} ${ry}`;
    if (points[points.length - 1] !== point) points.push(point);
  }

  // Islands smaller than a couple of pixels are noise at this resolution.
  if (points.length < 4) return null;

  return { d: `M ${points.join(" L ")} Z`, bbox: [minX, minY, maxX, maxY] };
}

function main() {
  const topology = JSON.parse(fs.readFileSync(SOURCE, "utf-8")) as Topology;
  const collection = feature(
    topology,
    topology.objects.countries,
  ) as unknown as GeoJSON.FeatureCollection;

  const shapes: Shape[] = [];
  const add = (ring: Ring) => {
    const shape = ringToShape(ring);
    if (shape) shapes.push(shape);
  };

  for (const f of collection.features) {
    const geom = f.geometry;
    if (geom.type === "Polygon") {
      for (const ring of geom.coordinates) add(ring as Ring);
    } else if (geom.type === "MultiPolygon") {
      for (const poly of geom.coordinates) for (const ring of poly) add(ring as Ring);
    }
  }

  const body = `// Generated by scripts/generate-world-map.ts. Do not edit by hand.
// Country outlines in the Mercator space defined by lib/travels/projection.ts.

export interface WorldShape {
  d: string;
  bbox: readonly [number, number, number, number];
}

export const WORLD_SHAPES: readonly WorldShape[] = ${JSON.stringify(shapes)};
`;

  fs.writeFileSync(OUT, body);
  const kb = Math.round(Buffer.byteLength(body) / 1024);
  console.log(
    `Wrote ${shapes.length} rings to ${path.relative(process.cwd(), OUT)} (${kb} KB).`,
  );
}

main();
